# Generated by Django 3.1.5 on 2022-04-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('location', models.CharField(max_length=50, verbose_name='город')),
                ('logo', models.URLField(default='https://place-hold.it/100x60', verbose_name='логотип')),
                ('description', models.TextField(verbose_name='описание')),
                ('employee_count', models.PositiveIntegerField(verbose_name='количество сотрудников')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='код')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('picture', models.URLField(default='https://place-hold.it/100x60', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('skills', models.TextField(verbose_name='навыки')),
                ('description', models.TextField(verbose_name='описание')),
                ('salary_min', models.PositiveIntegerField(verbose_name='минимальная зарплата')),
                ('salary_max', models.PositiveIntegerField(verbose_name='максимальная зарплата')),
                ('published_at', models.DateField(verbose_name='дата публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.company', verbose_name='компания')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='vacancies.specialty', verbose_name='специализация')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
